INSERT INTO researchers (name, email, bsl_clearance, department) VALUES
('Dr. Alice Vance', 'alice.vance@vellora.bio', 1, 'Molecular Biology'),
('Dr. Bob Smith', 'bob.smith@vellora.bio', 2, 'Genomics'),
('Dr. Clara Oswald', 'clara.oswald@vellora.bio', 3, 'Virology & Vectors'),
('Dr. David Banner', 'david.banner@vellora.bio', 4, 'High Containment Lab');

INSERT INTO genetic_payloads (name, sequence, risk_tier, created_by) VALUES
('GFP Marker Construct', 'ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAGGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA', 1, 1),
('CRISPR Cas9 Target Region', 'GGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAG', 2, 2),
('Attenuated Viral Vector Component', 'ATGCGTACGTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAG', 3, 3),
('High Risk Regulatory Construct', 'ATGGCCGACGACAAGCAGAAAAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATC', 4, 4);

INSERT INTO synthesis_jobs (researcher_id, payload_id, status, rejection_reason) VALUES
(1, 1, 'COMPLETED', NULL),
(2, 2, 'APPROVED', NULL),
(1, 3, 'REJECTED', 'Researcher BSL clearance level (1) is insufficient for payload risk tier (3).');

INSERT INTO safety_simulations (payload_id, off_target_score, status, details) VALUES
(1, 0.02, 'PASSED', 'Zero high-risk off-target alignments detected across Human Reference Genome GRCh38.'),
(2, 0.15, 'PASSED', 'Minor non-coding off-target matches identified with score < 0.20.'),
(3, 0.78, 'WARNING', 'Potential sequence homology with off-target regulatory regions.');
